### ISSUE TITLE
Support other isolate impl

### ISSUE THREAD

**Issue by windrunner414** [Sach97/Worker#4]
Now dart:isolate doesn't support platform channel, so we can't use plugin in isolate. we can add a custom spawn function to use flutter_isolate.By this we can use platform channel in isolate.We can also easily switch back to dart:isolate when it support platform channel.It won't bring any breaking changes.

```
Worker worker = Worker(poolSize: 4, spawn: FlutterIsolate.spawn); // use flutter_isolate
Worker worker = Worker(poolSize: 4); // use dart:isolate
```
Notice that if we want close worker, we should explicit termination with kill() because the event loop will not terminate in flutter_isolate

**Comment by windrunner414** [comment]
i will implement it and file a pr

**Comment by windrunner414** [comment]
pls give u opinion, thx

**Comment by windrunner414** [comment]
flutter_isolate doesn't support send a regular dart instance.

**Comment by sachaarbonel** [comment]
Hi @windrunner414, I'm sorry I never received the notif.
